export * from "./dashboard";
export * from "./login";
export * from "./registration";
export * from "./page-not-found";
export * from "./students";
export * from "./yearsetup";
export * from "./section";
export * from "./logout";
export * from "./main"
