export var FormItemFieldType;
(function (FormItemFieldType) {
    FormItemFieldType[FormItemFieldType["TEXT"] = 0] = "TEXT";
    FormItemFieldType[FormItemFieldType["INPUT"] = 1] = "INPUT";
    FormItemFieldType[FormItemFieldType["EMAIL"] = 2] = "EMAIL";
    FormItemFieldType[FormItemFieldType["SEARCH"] = 3] = "SEARCH";
    FormItemFieldType[FormItemFieldType["NUMBER"] = 4] = "NUMBER";
    FormItemFieldType[FormItemFieldType["DATE"] = 5] = "DATE";
    FormItemFieldType[FormItemFieldType["DATE_PICKER"] = 6] = "DATE_PICKER";
    FormItemFieldType[FormItemFieldType["DATE_RANGE"] = 7] = "DATE_RANGE";
    FormItemFieldType[FormItemFieldType["SELECT"] = 8] = "SELECT";
    FormItemFieldType[FormItemFieldType["SELECT_LIST"] = 9] = "SELECT_LIST";
    FormItemFieldType[FormItemFieldType["DROPDOWN"] = 10] = "DROPDOWN";
    FormItemFieldType[FormItemFieldType["SWITCH"] = 11] = "SWITCH";
    FormItemFieldType[FormItemFieldType["DIVIDER"] = 12] = "DIVIDER";
    FormItemFieldType[FormItemFieldType["TEXTAREA"] = 13] = "TEXTAREA";
    FormItemFieldType[FormItemFieldType["CUSTOM"] = 14] = "CUSTOM";
    FormItemFieldType[FormItemFieldType["PASSWORD"] = 15] = "PASSWORD";
    FormItemFieldType[FormItemFieldType["TIME"] = 16] = "TIME";
    FormItemFieldType[FormItemFieldType["TIME_PICKER"] = 17] = "TIME_PICKER";
    FormItemFieldType[FormItemFieldType["TIME_RANGE"] = 18] = "TIME_RANGE";
    FormItemFieldType[FormItemFieldType["RADIO"] = 19] = "RADIO";
    FormItemFieldType[FormItemFieldType["RADIOGROUP"] = 20] = "RADIOGROUP";
    FormItemFieldType[FormItemFieldType["CHECKBOX"] = 21] = "CHECKBOX";
    FormItemFieldType[FormItemFieldType["HIDDEN"] = 22] = "HIDDEN";
    FormItemFieldType[FormItemFieldType["TIME_RANGE_PICKER"] = 23] = "TIME_RANGE_PICKER";
    FormItemFieldType[FormItemFieldType["COLOR_PICKER"] = 24] = "COLOR_PICKER";
})(FormItemFieldType || (FormItemFieldType = {}));
